
import { Thought, Weight } from '../types';

export const generateGoogleCalendarUrl = (thought: Thought): string => {
  const baseUrl = "https://calendar.google.com/calendar/render";
  const action = "TEMPLATE";
  
  // Basic Details
  const text = encodeURIComponent(thought.content);
  
  let priorityText = 'Casual';
  if (thought.weight === 'URGENT') priorityText = 'Urgent';
  if (thought.weight === 'IMPORTANT') priorityText = 'Important';

  const details = encodeURIComponent(
    `Generated by Flux.\n\nPriority: ${priorityText}\nReasoning: ${thought.aiReasoning || 'N/A'}`
  );

  // Dates
  // Default to starting now, ending in 1 hour
  const now = new Date();
  // Round up to nearest 15 minutes
  const start = new Date(Math.ceil(now.getTime() / (15 * 60 * 1000)) * (15 * 60 * 1000));
  const end = new Date(start.getTime() + 60 * 60 * 1000); // 1 hour duration

  const formatDate = (date: Date) => {
    return date.toISOString().replace(/-|:|\.\d\d\d/g, "");
  };

  const dates = `${formatDate(start)}/${formatDate(end)}`;

  // Construct URL
  let url = `${baseUrl}?action=${action}&text=${text}&details=${details}&dates=${dates}`;

  return url;
};
